all: kilo pkilo new

kilo: kilo.c
	$(CC) kilo.c -o kilo -Wall -Wextra -pedantic -std=c99
pkilo: pKilo.c
	$(CC) pKilo.c -o pkilo -Wall -Wextra -pedantic -std=c99
new: new.c
	$(CC) new.c -o new -Wall -Wextra -pedantic -std=c99